// flow-typed signature: 5377e7fc1ddbad0d7af6b7fd90a619f9
// flow-typed version: <<STUB>>/ios-deploy_v^1.9.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ios-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ios-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ios-deploy/src/scripts/check_reqs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ios-deploy/src/scripts/check_reqs.js' {
  declare module.exports: $Exports<'ios-deploy/src/scripts/check_reqs'>;
}
