// flow-typed signature: f4451bb1e0d695e5bb4f0d60ece50788
// flow-typed version: <<STUB>>/react-native-video_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-video/Video' {
  declare module.exports: any;
}

declare module 'react-native-video/VideoResizeMode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-video/Video.js' {
  declare module.exports: $Exports<'react-native-video/Video'>;
}
declare module 'react-native-video/VideoResizeMode.js' {
  declare module.exports: $Exports<'react-native-video/VideoResizeMode'>;
}
