// flow-typed signature: 79db0ada1db811e006777e926b458f80
// flow-typed version: <<STUB>>/redux-persist_vrt2zz/redux-persist#v5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist/src/constants' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createMigrate' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createPersistoid' {
  declare module.exports: any;
}

declare module 'redux-persist/src/createTransform' {
  declare module.exports: any;
}

declare module 'redux-persist/src/getStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/index' {
  declare module.exports: any;
}

declare module 'redux-persist/src/integration/getStoredStateMigrateV4' {
  declare module.exports: any;
}

declare module 'redux-persist/src/integration/react' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistReducer' {
  declare module.exports: any;
}

declare module 'redux-persist/src/persistStore' {
  declare module.exports: any;
}

declare module 'redux-persist/src/purgeStoredState' {
  declare module.exports: any;
}

declare module 'redux-persist/src/stateReconciler' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/createWebStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/getStorage' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/index' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/index.native' {
  declare module.exports: any;
}

declare module 'redux-persist/src/storage/session' {
  declare module.exports: any;
}

declare module 'redux-persist/src/types' {
  declare module.exports: any;
}

declare module 'redux-persist/src/utils/curry' {
  declare module.exports: any;
}

declare module 'redux-persist/tests/complete.spec' {
  declare module.exports: any;
}

declare module 'redux-persist/tests/persistReducer.spec' {
  declare module.exports: any;
}

declare module 'redux-persist/tests/persistStore.spec' {
  declare module.exports: any;
}

declare module 'redux-persist/tests/utils/sleep' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist/src/constants.js' {
  declare module.exports: $Exports<'redux-persist/src/constants'>;
}
declare module 'redux-persist/src/createMigrate.js' {
  declare module.exports: $Exports<'redux-persist/src/createMigrate'>;
}
declare module 'redux-persist/src/createPersistoid.js' {
  declare module.exports: $Exports<'redux-persist/src/createPersistoid'>;
}
declare module 'redux-persist/src/createTransform.js' {
  declare module.exports: $Exports<'redux-persist/src/createTransform'>;
}
declare module 'redux-persist/src/getStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/getStoredState'>;
}
declare module 'redux-persist/src/index.js' {
  declare module.exports: $Exports<'redux-persist/src/index'>;
}
declare module 'redux-persist/src/integration/getStoredStateMigrateV4.js' {
  declare module.exports: $Exports<'redux-persist/src/integration/getStoredStateMigrateV4'>;
}
declare module 'redux-persist/src/integration/react.js' {
  declare module.exports: $Exports<'redux-persist/src/integration/react'>;
}
declare module 'redux-persist/src/persistReducer.js' {
  declare module.exports: $Exports<'redux-persist/src/persistReducer'>;
}
declare module 'redux-persist/src/persistStore.js' {
  declare module.exports: $Exports<'redux-persist/src/persistStore'>;
}
declare module 'redux-persist/src/purgeStoredState.js' {
  declare module.exports: $Exports<'redux-persist/src/purgeStoredState'>;
}
declare module 'redux-persist/src/stateReconciler.js' {
  declare module.exports: $Exports<'redux-persist/src/stateReconciler'>;
}
declare module 'redux-persist/src/storage/createWebStorage.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/createWebStorage'>;
}
declare module 'redux-persist/src/storage/getStorage.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/getStorage'>;
}
declare module 'redux-persist/src/storage/index.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/index'>;
}
declare module 'redux-persist/src/storage/index.native.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/index.native'>;
}
declare module 'redux-persist/src/storage/session.js' {
  declare module.exports: $Exports<'redux-persist/src/storage/session'>;
}
declare module 'redux-persist/src/types.js' {
  declare module.exports: $Exports<'redux-persist/src/types'>;
}
declare module 'redux-persist/src/utils/curry.js' {
  declare module.exports: $Exports<'redux-persist/src/utils/curry'>;
}
declare module 'redux-persist/tests/complete.spec.js' {
  declare module.exports: $Exports<'redux-persist/tests/complete.spec'>;
}
declare module 'redux-persist/tests/persistReducer.spec.js' {
  declare module.exports: $Exports<'redux-persist/tests/persistReducer.spec'>;
}
declare module 'redux-persist/tests/persistStore.spec.js' {
  declare module.exports: $Exports<'redux-persist/tests/persistStore.spec'>;
}
declare module 'redux-persist/tests/utils/sleep.js' {
  declare module.exports: $Exports<'redux-persist/tests/utils/sleep'>;
}
